### ISSUE TITLE
Starting Rethinkdb

### ISSUE THREAD

**Issue by clevernyyyy** [crftd/post3ree-boilerplate#20]
What exactly do you mean in the README by
> set connect to it (app/db/services.js).

Right now, if I run `rethinkdb` from `app/` in one terminal tab and in another tab run `npm i && npm start`, I get an error upon startup.

Normally, I would go look at the error and try to deduce what the problem was, but this happening on startup makes me feel like I did something wrong.  The only thing from the README.md that didn't make 100% sense to me was that "set connect to it (app/db/services.js)", so it is extremely likely that this is me just being dumb.

Error:

```
TypeError: Cannot read property 'isAuthenticated' of undefined
    at Function.mapToProps (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/client/containers/ContainerWrapperHOC.js:35:22)
    at mapToPropsProxy (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:92)
    at Function.detectFactoryAndVerify (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/connect/wrapMapToProps.js:63:19)
    at mapToPropsProxy (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/connect/wrapMapToProps.js:54:46)
    at handleFirstCall (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/connect/selectorFactory.js:37:18)
    at pureFinalPropsSelector (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/connect/selectorFactory.js:85:81)
    at Object.runComponentSelector [as run] (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/components/connectAdvanced.js:43:25)
    at Connect.initSelector (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/components/connectAdvanced.js:195:23)
    at new Connect (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-redux/lib/components/connectAdvanced.js:136:15)
    at /Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:292:18
    at measureLifeCyclePerf (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:73:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:291:16)
    at ReactCompositeComponentWrapper._constructComponent (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:282:19)
    at ReactCompositeComponentWrapper.mountComponent (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:185:21)
    at Object.mountComponent (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactReconciler.js:43:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/clevernyyyy/develop/infosec/post3ree-boilerplate/node_modules/react-dom/lib/ReactCompositeComponent.js:368:34)
```

**Comment by Amazing-Space-Invader** [comment]
Hello @clevernyyyy
This error mean `isAuthenticated ` is not defined in redux store but connected in `ContainerWrapperHOC`. You need specify this value in redux store.

https://github.com/crftd/post3ree-boilerplate/blob/master/client/containers/ContainerWrapperHOC.js#L35
https://github.com/crftd/post3ree-boilerplate/blob/master/client/redux/index.js#L5

**Comment by hex22a** [comment]
Hi @clevernyyyy and thank you for your interest.
Unfortunately this repo is no longer maintened and I would recommend you to try one of starter kits - https://reactjs.org/community/starter-kits.html
